import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { Providers } from "@/utils/providers"
import { Header } from "@/components/layout/Header/index"
import { HeroSection } from "@/components/layout/HeroSection/index"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <Providers>
                    <Header />
                    <main className='flex min-h-screen flex-col items-center px-16 py-24 md:p-24 gap-10'>
                        <div className='w-full'>
                            <HeroSection />
                        </div>
                        {children}
                    </main>
                </Providers>
            </body>
        </html>
    )
}
